import type { PackageJson } from 'pkg-types'
import type { FnclipOptions } from '../cli/options'
import * as fs from 'node:fs/promises'
import * as pkg from 'empathic/package'
import * as path from 'pathe'
import { fnclipPath } from '..'
import { exists } from './tools'

export * from './fnclip/index'
export * from './tools'

export async function getMeta() {
  const res: Record<string, string> = JSON.parse(await fs.readFile(path.join(fnclipPath, 'funcs-meta.json'), 'utf-8'))
  return res
}

export function ensureExt(fullname: string, ext: string) {
  return path.extname(fullname) ? fullname : `${fullname}${ext}`
}

export async function isTypescript(cwd: string) {
  const packageJsonPath = pkg.up({ cwd })
  if (!packageJsonPath)
    return

  const obj: PackageJson = JSON.parse(await fs.readFile(packageJsonPath, 'utf-8'))
  return !!(obj.dependencies?.typescript || obj.devDependencies?.typescript)
}

const exportContent = (to: string) => `export * from '${to}';`
export async function updateIndex(opts: FnclipOptions, dry = false) {
  if (!opts.index)
    return

  const meta = await getMeta()
  const metaSet = new Set(Object.keys(meta))
  const dirPath = path.join(opts.cwd, opts.dir)
  const indexPathMaybeExt = path.join(opts.cwd, opts.indexPath)

  // check exist index file
  let indexRealPath: string
  for (const ext of ['.ts', '.js']) {
    const targetPath = ensureExt(indexPathMaybeExt, ext)
    if (await exists(targetPath)) {
      indexRealPath = targetPath
      break
    }
  }

  indexRealPath ??= ensureExt(indexPathMaybeExt, (opts.ts ? '.ts' : '.js'))
  await fs.open(indexRealPath, 'a')

  const funcs = [...new Set(
    (await fs.readdir(dirPath)).map(name => name.replace(/\.(?:js|ts|d\.ts)$/, '')),
  )]
  dry || await fs.writeFile(indexRealPath, addIgnoreToContent(
    funcs
      .filter(func => metaSet.has(func))
      .map(name => exportContent(relativeImportPath(
        path.dirname(indexRealPath),
        path.join(dirPath, name),
      )))
      .join('\n'),
  ))
}

export function addIgnoreToContent(content: string) {
  const comments = `/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// biome-ignore lint: disable
// Generated by fnclip

`
  return content.includes(comments) ? content : comments + content
}

export function relativeImportPath(from: string, to: string) {
  const rel = path.relative(from, to)
  return rel.startsWith('.') ? rel : `./${rel}`
}
